# Generated by Django 3.2.25 on 2024-10-17 22:43

from django.db import migrations, models
import django.db.models.deletion
import djangocms_icon.fields
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_icon', '0003_alter_icon_cmsplugin_ptr'),
    ]

    operations = [
        migrations.CreateModel(
            name='IconTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('icon_new', djangocms_icon.fields.Icon(blank=True, default='', max_length=255, verbose_name='Icon')),
                ('template_new', models.CharField(choices=[('default', 'Default')], default='default', max_length=255, verbose_name='Template')),
                ('label_new', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='djangocms_icon.icon')),
            ],
            options={
                'verbose_name': 'icon Translation',
                'db_table': 'djangocms_icon_icon_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
