# Generated by Django 3.2.25 on 2024-10-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_icon', '0004_icontranslation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icontranslation',
            old_name='icon_new',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='icontranslation',
            old_name='label_new',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='icontranslation',
            old_name='template_new',
            new_name='template',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='label',
        ),
        migrations.RemoveField(
            model_name='icon',
            name='template',
        ),
    ]
